import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import { Toaster } from 'sonner';
import QueryProvider from '@/providers/query.provider';
import './globals.css';

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Outfitters',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={roboto.className}>
          <Toaster richColors />
          <div className="flex min-h-screen flex-col">
            <Navbar />
            {children}
            <div className="mt-auto">
              <Footer />
            </div>
          </div>
        </body>
      </QueryProvider>
    </html>
  );
}
